# Generated by Django 4.1.2 on 2022-11-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('selling_price', models.FloatField(max_length=200, null=True)),
                ('discount_price', models.FloatField(max_length=200, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('apppro', models.TextField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('MN', 'Mens'), ('WM', 'Women'), ('KD', 'Kids')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
